
nohup python3 main.py --gpu_id $g --model_idx 0  --exp 3 --data_name Beauty --contras_target interk --contras_k 8 --contras_loss_weight 0.01  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.2  > con3/0.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 1  --exp 3 --data_name Beauty --contras_target interk --contras_k 8 --contras_loss_weight 0.02  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.2  > con3/1.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 2  --exp 3 --data_name Beauty --contras_target interk --contras_k 8 --contras_loss_weight 0.05  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.2  > con3/2.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 3  --exp 3 --data_name Beauty --contras_target interk --contras_k 8 --contras_loss_weight 0.1  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.2  > con3/3.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 4  --exp 3 --data_name Beauty --contras_target interk --contras_k 10 --contras_loss_weight 0.01  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.2  > con3/4.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 5  --exp 3 --data_name Beauty --contras_target interk --contras_k 10 --contras_loss_weight 0.02  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.2  > con3/5.log 2>&1

nohup python3 main.py --gpu_id $g --model_idx 6  --exp 3 --data_name Beauty --contras_target interk --contras_k 10 --contras_loss_weight 0.05  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.2  > con3/6.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 7  --exp 3 --data_name Beauty --contras_target interk --contras_k 10 --contras_loss_weight 0.1  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.2  > con3/7.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 8  --exp 3 --data_name Beauty --contras_target interk --contras_k 15 --contras_loss_weight 0.01  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.2  > con3/8.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 9  --exp 3 --data_name Beauty --contras_target interk --contras_k 15 --contras_loss_weight 0.02  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.2  > con3/9.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 10  --exp 3 --data_name Beauty --contras_target interk --contras_k 15 --contras_loss_weight 0.05  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.2  > con3/10.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 11  --exp 3 --data_name Beauty --contras_target interk --contras_k 15 --contras_loss_weight 0.1  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.2  > con3/11.log 2>&1

nohup python3 main.py --gpu_id $g --model_idx 12  --exp 3 --data_name Beauty --contras_target avgk --contras_k 8 --contras_loss_weight 0.01  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.2  > con3/12.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 13  --exp 3 --data_name Beauty --contras_target avgk --contras_k 8 --contras_loss_weight 0.02  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.2  > con3/13.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 14  --exp 3 --data_name Beauty --contras_target avgk --contras_k 8 --contras_loss_weight 0.05  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.2  > con3/14.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 15  --exp 3 --data_name Beauty --contras_target avgk --contras_k 8 --contras_loss_weight 0.1  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.2  > con3/15.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 16  --exp 3 --data_name Beauty --contras_target avgk --contras_k 10 --contras_loss_weight 0.01  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.2  > con3/16.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 17  --exp 3 --data_name Beauty --contras_target avgk --contras_k 10 --contras_loss_weight 0.02  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.2  > con3/17.log 2>&1

nohup python3 main.py --gpu_id $g --model_idx 18  --exp 3 --data_name Beauty --contras_target avgk --contras_k 10 --contras_loss_weight 0.05  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.2  > con3/18.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 19  --exp 3 --data_name Beauty --contras_target avgk --contras_k 10 --contras_loss_weight 0.1  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.2  > con3/19.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 20  --exp 3 --data_name Beauty --contras_target avgk --contras_k 15 --contras_loss_weight 0.01  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.2  > con3/20.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 21  --exp 3 --data_name Beauty --contras_target avgk --contras_k 15 --contras_loss_weight 0.02  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.2  > con3/21.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 22  --exp 3 --data_name Beauty --contras_target avgk --contras_k 15 --contras_loss_weight 0.05  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.2  > con3/22.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 23  --exp 3 --data_name Beauty --contras_target avgk --contras_k 15 --contras_loss_weight 0.1  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.2  > con3/23.log 2>&1
