
nohup python3 main.py --gpu_id $g --model_idx 0  --exp 4 --data_name Beauty --contras_target interk --contras_k 8 --contras_loss_weight 0.01  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.5  > con4/0.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 1  --exp 4 --data_name Beauty --contras_target interk --contras_k 8 --contras_loss_weight 0.02  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.5  > con4/1.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 2  --exp 4 --data_name Beauty --contras_target interk --contras_k 8 --contras_loss_weight 0.05  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.5  > con4/2.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 3  --exp 4 --data_name Beauty --contras_target interk --contras_k 8 --contras_loss_weight 0.1  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.5  > con4/3.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 4  --exp 4 --data_name Beauty --contras_target interk --contras_k 10 --contras_loss_weight 0.01  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.5  > con4/4.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 5  --exp 4 --data_name Beauty --contras_target interk --contras_k 10 --contras_loss_weight 0.02  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.5  > con4/5.log 2>&1

nohup python3 main.py --gpu_id $g --model_idx 6  --exp 4 --data_name Beauty --contras_target interk --contras_k 10 --contras_loss_weight 0.05  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.5  > con4/6.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 7  --exp 4 --data_name Beauty --contras_target interk --contras_k 10 --contras_loss_weight 0.1  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.5  > con4/7.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 8  --exp 4 --data_name Beauty --contras_target interk --contras_k 15 --contras_loss_weight 0.01  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.5  > con4/8.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 9  --exp 4 --data_name Beauty --contras_target interk --contras_k 15 --contras_loss_weight 0.02  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.5  > con4/9.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 10  --exp 4 --data_name Beauty --contras_target interk --contras_k 15 --contras_loss_weight 0.05  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.5  > con4/10.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 11  --exp 4 --data_name Beauty --contras_target interk --contras_k 15 --contras_loss_weight 0.1  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.5  > con4/11.log 2>&1

nohup python3 main.py --gpu_id $g --model_idx 12  --exp 4 --data_name Beauty --contras_target avgk --contras_k 8 --contras_loss_weight 0.01  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.5  > con4/12.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 13  --exp 4 --data_name Beauty --contras_target avgk --contras_k 8 --contras_loss_weight 0.02  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.5  > con4/13.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 14  --exp 4 --data_name Beauty --contras_target avgk --contras_k 8 --contras_loss_weight 0.05  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.5  > con4/14.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 15  --exp 4 --data_name Beauty --contras_target avgk --contras_k 8 --contras_loss_weight 0.1  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.5  > con4/15.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 16  --exp 4 --data_name Beauty --contras_target avgk --contras_k 10 --contras_loss_weight 0.01  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.5  > con4/16.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 17  --exp 4 --data_name Beauty --contras_target avgk --contras_k 10 --contras_loss_weight 0.02  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.5  > con4/17.log 2>&1

nohup python3 main.py --gpu_id $g --model_idx 18  --exp 4 --data_name Beauty --contras_target avgk --contras_k 10 --contras_loss_weight 0.05  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.5  > con4/18.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 19  --exp 4 --data_name Beauty --contras_target avgk --contras_k 10 --contras_loss_weight 0.1  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.5  > con4/19.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 20  --exp 4 --data_name Beauty --contras_target avgk --contras_k 15 --contras_loss_weight 0.01  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.5  > con4/20.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 21  --exp 4 --data_name Beauty --contras_target avgk --contras_k 15 --contras_loss_weight 0.02  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.5  > con4/21.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 22  --exp 4 --data_name Beauty --contras_target avgk --contras_k 15 --contras_loss_weight 0.05  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.5  > con4/22.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 23  --exp 4 --data_name Beauty --contras_target avgk --contras_k 15 --contras_loss_weight 0.1  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.5  > con4/23.log 2>&1
