
nohup python3 main.py --gpu_id $g --model_idx 0  --exp 7 --data_name Beauty --contras_target interk --contras_k 8 --contras_loss_weight 0.01  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.1  > con7/0.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 1  --exp 7 --data_name Beauty --contras_target interk --contras_k 8 --contras_loss_weight 0.02  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.1  > con7/1.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 2  --exp 7 --data_name Beauty --contras_target interk --contras_k 8 --contras_loss_weight 0.05  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.1  > con7/2.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 3  --exp 7 --data_name Beauty --contras_target interk --contras_k 8 --contras_loss_weight 0.1  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.1  > con7/3.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 4  --exp 7 --data_name Beauty --contras_target interk --contras_k 10 --contras_loss_weight 0.01  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.1  > con7/4.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 5  --exp 7 --data_name Beauty --contras_target interk --contras_k 10 --contras_loss_weight 0.02  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.1  > con7/5.log 2>&1

nohup python3 main.py --gpu_id $g --model_idx 6  --exp 7 --data_name Beauty --contras_target interk --contras_k 10 --contras_loss_weight 0.05  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.1  > con7/6.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 7  --exp 7 --data_name Beauty --contras_target interk --contras_k 10 --contras_loss_weight 0.1  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.1  > con7/7.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 8  --exp 7 --data_name Beauty --contras_target interk --contras_k 15 --contras_loss_weight 0.01  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.1  > con7/8.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 9  --exp 7 --data_name Beauty --contras_target interk --contras_k 15 --contras_loss_weight 0.02  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.1  > con7/9.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 10  --exp 7 --data_name Beauty --contras_target interk --contras_k 15 --contras_loss_weight 0.05  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.1  > con7/10.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 11  --exp 7 --data_name Beauty --contras_target interk --contras_k 15 --contras_loss_weight 0.1  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.1  > con7/11.log 2>&1

nohup python3 main.py --gpu_id $g --model_idx 12  --exp 7 --data_name Beauty --contras_target avgk --contras_k 8 --contras_loss_weight 0.01  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.1  > con7/12.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 13  --exp 7 --data_name Beauty --contras_target avgk --contras_k 8 --contras_loss_weight 0.02  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.1  > con7/13.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 14  --exp 7 --data_name Beauty --contras_target avgk --contras_k 8 --contras_loss_weight 0.05  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.1  > con7/14.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 15  --exp 7 --data_name Beauty --contras_target avgk --contras_k 8 --contras_loss_weight 0.1  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.1  > con7/15.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 16  --exp 7 --data_name Beauty --contras_target avgk --contras_k 10 --contras_loss_weight 0.01  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.1  > con7/16.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 17  --exp 7 --data_name Beauty --contras_target avgk --contras_k 10 --contras_loss_weight 0.02  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.1  > con7/17.log 2>&1

nohup python3 main.py --gpu_id $g --model_idx 18  --exp 7 --data_name Beauty --contras_target avgk --contras_k 10 --contras_loss_weight 0.05  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.1  > con7/18.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 19  --exp 7 --data_name Beauty --contras_target avgk --contras_k 10 --contras_loss_weight 0.1  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.1  > con7/19.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 20  --exp 7 --data_name Beauty --contras_target avgk --contras_k 15 --contras_loss_weight 0.01  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.1  > con7/20.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 21  --exp 7 --data_name Beauty --contras_target avgk --contras_k 15 --contras_loss_weight 0.02  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.1  > con7/21.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 22  --exp 7 --data_name Beauty --contras_target avgk --contras_k 15 --contras_loss_weight 0.05  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.1  > con7/22.log 2>&1
nohup python3 main.py --gpu_id $g --model_idx 23  --exp 7 --data_name Beauty --contras_target avgk --contras_k 15 --contras_loss_weight 0.1  --gen_loss_type full-softmax --gen_loss_weight 1.0   --model_shared_type full --gen_attention_probs_dropout_prob 0.1  > con7/23.log 2>&1
